[workspace]
authors = ["Suraj Anand <surajk610@gmail.com>"]
channels = ["conda-forge"]
name = "garcon"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.1,<3"
jupyter = ">=1.1.1,<2"
pytorch = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
torchaudio = ">=2.7.1,<3"
pyarrow = ">=12.0.0"
ipykernel = ">=6.29.5,<7"
plotly = ">=6.2.0,<7"

[pypi-dependencies]
jupyterlab-nvidia-nsight = ">=0.7.0, <0.8"
transformer-lens = ">=2.15.4, <3"
nnsight = ">=0.4.10, <0.5"
gradio = ">=5.38.0, <6"
circuitsvis = ">=1.43.3, <2"
